export const topData = [
  {
    icon: "images/icon-facebook.svg",
    name: "@nathanf",
    followers: 1987,
    todayFollowers: 12,
    todayStatus: "images/icon-up.svg",
    borderTop: "bg-[hsl(208,92%,53%)]",
  },
  {
    icon: "images/icon-twitter.svg",
    name: "@nathanf",
    followers: 1044,
    todayFollowers: 99,
    todayStatus: "images/icon-up.svg",
    borderTop: "bg-[hsl(203,89%,53%)]",
  },
  {
    icon: "images/icon-instagram.svg",
    name: "@realnathanf",
    followers: "11k",
    todayFollowers: 1099,
    todayStatus: "images/icon-up.svg",
    borderTop: "bg-gradient-to-r from-[hsl(37,97%,70%)] to-[hsl(329,70%,58%)]",
  },
  {
    icon: "images/icon-youtube.svg",
    name: "Narthan F.",
    followers: 8239,
    todayFollowers: 144,
    todayStatus: "images/icon-down.svg",
    borderTop: "bg-[hsl(348,97%,39%)]",
  },
];

export const overviewData = [
  {
    title: "Page Views",
    icon: "images/icon-facebook.svg",
    view: "87",
    percentage: 3,
    todayStatus: "images/icon-up.svg",
  },
  {
    title: "Likes",
    icon: "images/icon-facebook.svg",
    view: "52",
    percentage: 2,
    todayStatus: "images/icon-down.svg",
  },
  {
    title: "Likes",
    icon: "images/icon-instagram.svg",
    view: "5462",
    percentage: 2257,
    todayStatus: "images/icon-up.svg",
  },
  {
    title: "Profile Views",
    icon: "images/icon-instagram.svg",
    view: "52k",
    percentage: 1375,
    todayStatus: "images/icon-up.svg",
  },
  {
    title: "Retweets",
    icon: "images/icon-twitter.svg",
    view: "117",
    percentage: 303,
    todayStatus: "images/icon-up.svg",
  },
  {
    title: "Page Views",
    icon: "images/icon-twitter.svg",
    view: "507",
    percentage: 553,
    todayStatus: "images/icon-up.svg",
  },
  {
    title: "Likes",
    icon: "images/icon-youtube.svg",
    view: "107",
    percentage: 19,
    todayStatus: "images/icon-down.svg",
  },
  {
    title: "Page Views",
    icon: "images/icon-youtube.svg",
    view: "1407",
    percentage: 12,
    todayStatus: "images/icon-down.svg",
  },
];
